# Generated by Django 5.2.6 on 2025-09-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_ticket_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='capacity',
        ),
    ]
