# Generated by Django 5.2.6 on 2025-09-25 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_ticket_unique_together_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seat',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='rows_business',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='rows_economy',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='rows_first_class',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='seats_per_row_business',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='seats_per_row_economy',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='seats_per_row_first_class',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seat_class',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seat_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seat_preference',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='airplane',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='business_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='economy_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='first_class_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='return_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_orders', to='tasks.flight'),
        ),
        migrations.AddField(
            model_name='order',
            name='ticket_type',
            field=models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], default='one_way', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='direction',
            field=models.CharField(choices=[('outbound', 'Outbound'), ('return', 'Return')], default='outbound', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tasks.order'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_class',
            field=models.CharField(blank=True, choices=[('economy', 'Economy'), ('business', 'Business'), ('first_class', 'First Class')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='return_flight',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
