# Generated by Django 5.2.6 on 2025-09-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_order_seat_rename_price_order_total_price_and_more'),
    ]

    operations = [
    ]
