# Generated by Django 5.2.6 on 2025-10-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_ticket_order_alter_ticket_seat_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tickets_data',
            field=models.JSONField(blank=True, help_text='Stored ticket data for later creation', null=True),
        ),
    ]
