# Generated by Django 5.2.6 on 2025-10-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
