# Generated by Django 5.2.6 on 2025-09-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_avatar_user_avatar_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_google_user',
        ),
    ]
